### ISSUE TITLE
[Request]mod ideas

### ISSUE THREAD

**Issue by 88onme** [FTBTeam/FTB-Unstable-1.14#12]
Just wanted to put some mods I love for 1.14 but are not in the pack

1. Bad Beacon https://www.curseforge.com/minecraft/mc-mods/bad-beacon
Adds a new beacon block that has negative potion effects

2. Simple Farming https://www.curseforge.com/minecraft/mc-mods/simple-farming
Lots of convenient crops, bushes, meals, etc.

3. Campfire torches https://www.curseforge.com/minecraft/mc-mods/campfire-torches
You can cook sticks into torches on the campfire

**Comment by Sunekaer** [comment]
This pack is all about testing and bug finding.
Is there any testing reason to why you would like these mods in

**Comment by 88onme** [comment]
I think adding them will help test every mod. 1.14 forge is still in an early build, and it would be great to see which mods are compatible with each other and which mods conflict with each other. The only way to test a mod is to see if it can work with others. I think adding them to the pack will help test them together and also introduce them to other players and mod makers, making the community more unified and connected.

**Comment by Sunekaer** [comment]
1 and 3 these mods are very  simple mods with only one focus, wont be added.
2 i already said no to for now as there is other mods adding foods
