### ISSUE TITLE
[Request] Mystical Wildlife

### ISSUE THREAD

**Issue by Lykrast** [FTBTeam/FTB-Unstable-1.14#13]
[Mystical Wildlife](https://www.curseforge.com/minecraft/mc-mods/mystical-wildlife) is a simple mod that adds extra animals. It makes the game a bit more diverse and also makes a few resources (Leather, Dirt and some dyes) easier to get for what they're worth.

It works with Biomes O' Plenty (or any other biome mod) so there shouldn't be any issue. I'm not sure animals will spawn in existing chunks because of how animals spawn but they'll be here in new ones.

**Comment by Sunekaer** [comment]
This pack is all about testing and bug finding.
Is there any testing reason to why you would like this in

**Comment by Lykrast** [comment]
Not any particular one in that case, just thought it would fit nicely and wondering how well it would actually fit with the other mods.

Mb on not catching that the pack is mostly for experimental bug testing, it could be slightly more explicit on the cf page though.

**Comment by Sunekaer** [comment]
Added  in the newest version
