### ISSUE TITLE
Recipe Book

### ISSUE THREAD

**Issue by FlamingChainsawCannon** [FTBTeam/FTB-Unstable-1.14#15]
Whenever I click on the vanilla recipe book it crashed my game and the launcher reads 
" The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Method com/naxanria/nom/recipe/GrinderRecipe.func_194133_a(II)Z is abstract "

**Comment by Sunekaer** [comment]
Full log?

**Comment by Sunekaer** [comment]
https://github.com/Naxanria/nom/issues/2

**Comment by RudiHansen** [comment]
I get the same error, here is the crash report https://pastebin.com/FsexgkdR

**Comment by T0wel** [comment]
I have this same issue.

**Comment by Sunekaer** [comment]
fixed in newest version
