### ISSUE TITLE
Bug or intended?

### ISSUE THREAD

**Issue by baconbotmk1** [FTBTeam/FTB-Unstable-1.14#17]
I've traveled through the world and all of a sudden i got the effect "glowing" out of nowhere, now i can see all hostile mobs permanent

**Comment by NoBar94** [comment]
> I've traveled through the world and all of a sudden i got the effect "glowing" out of nowhere, now i can see all hostile mobs permanent

Confirmed, this also happened to me with no noticeable prompt. Will continue to try to cause it to happen!
![2019-08-28_10 32 44](https://user-images.githubusercontent.com/54633258/63865304-55431500-c97f-11e9-8725-649bed8b7335.png)


Also, it appears to happen locally in a specific chunk or two?
![2019-08-28_10 35 50](https://user-images.githubusercontent.com/54633258/63865521-b8cd4280-c97f-11e9-8886-9ce961d21482.png)

**Comment by Mntldisorder** [comment]
this is due the bell from the village update in vanilla, it shows hostile mobs as glowing in a certain radius, not sure how big tho

**Comment by NoBar94** [comment]
I'm not anywhere near a bell, but that would at least shed light on why they're glowing. I didn't know about the glowing effect from the bell though! Good to know!

**Comment by Sunekaer** [comment]
You can backup your world, and disable mod by mod to find what's causing it if it isn't the bell

**Comment by Vulcyn** [comment]
I had this same issue soon after loading up my world. It seems Something is causing the bell to be rung inside a village nearby. Breaking the bell stopped the effect after a minute or so.
