### ISSUE TITLE
Cactus growing next to solid blocks ... cactus farm broken

### ISSUE THREAD

**Issue by professorcraft1** [FTBTeam/FTB-Unstable-1.14#18]
I'm using FTB Unstable 1.14, release Version: 1.7.0 Minecraft Version: 1.14.4 (modded) forge-28.0.55

This is not a crash just super annoying since I was hoping to make a cactus farm.  I've been searching google and this issue log for similar reports and haven't found any so I thought I would post here.

Issue steps:

1. Make a 3 block high pillar of cobble, remove middle block.
2. Next to it place sand, and cactus on sand.
3. The cactus grows up, right next to and past the cobble block without breaking.

Expected behavior: Cactus breaks

Also might be related, but when I break the bottom block of a column of cactus, instead of all the blocks breaking just the bottom block breaks.

At first I thought it might relate to one of the mods in the pack, "Configurable Cane" but disabling that mod did not fix the issue.

PS This pack is amazing.  I tried (unsuccessfully) to make my own 1.14 pack and thankfully this pack makes it so I don't have to.  Thank you for putting it together and I look forward to seeing it develop further.

**Comment by professorcraft1** [comment]
Update: This seems related: https://bugs.mojang.com/browse/MC-44484

Reading through that bug report a few people report that it is fixed in a newer snapshot and others report that breaking the cactus and letting it regrow fixes the problem.  I'm curious if keeping the chunk loaded makes a difference, too.  Curious if other people are seeing this behavior.

**Comment by Sunekaer** [comment]
You can report this to forge, and maybe they will implement a fix

**Comment by Hokage3211** [comment]
This issue is not fixed in the latest version, and it is not a minecraft bug, configurable cane mod is interfering with the cactus growth, causing it to never break when blocks are next to it, removing or disabling the mod from the modpack fixes this issue.
