### ISSUE TITLE
[v1.8.1] Outdated Forge and/or crash

### ISSUE THREAD

**Issue by Excederus** [FTBTeam/FTB-Unstable-1.14#24]
When starting the pack in v1.8.1 without doing any changes the game prompts me that the mod "midnight" (nowhere to be found in the mods folder) needs Forge v28.1.10 instead of v28.1.8
But when I update to that Forge version the game just crashes ( [Log](https://pastebin.com/3gTvR7q5) ) before even showing the mojang screen

**Comment by Sunekaer** [comment]
Sorry about that ill get a fix out

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-unstable-1-14/files/2790781
