### ISSUE TITLE
Spectator mode has no flight

### ISSUE THREAD

**Issue by moon-st0ne** [FTBTeam/FTB-Unstable-1.14#3]
Entering spectator mode in the latest version of the pack (1.2.0) results in falling to your death in the void, as you have no collision and no flight. Creative mode is unaffected.

**Comment by Sunekaer** [comment]
Fixed in dev, just waiting for some mod updates before we can release a new version

**Comment by moon-st0ne** [comment]
I don't suppose there's a list of known bugfixes somewhere? GitHub seems to be mostly empty, if only 3 issue tickets is any indication.

**Comment by Sunekaer** [comment]
you'll have to look each mod and read their logs, there have been so many mod updates so I can't write them down

**Comment by Sunekaer** [comment]
https://www.curseforge.com/minecraft/modpacks/ftb-unstable-1-14/files/2762004
