### ISSUE TITLE
java launcher stuck "loading versions"

### ISSUE THREAD

**Issue by crunchynut609** [FTBTeam/FTB-Unstable-1.14#30]
whenever I press play on the modpack and it brings me to the launcher, it gets stuck on loading and loading versions

here is a copy and paste of the launcher log;

https://paste.feed-the-beast.com/view/04887ca5

**Comment by Sunekaer** [comment]
go to settings -> minecraft -> Launcher -> Launcher Method and set it to Native, that fixed it for me

**Comment by Alucabr** [comment]
I have the same problem with this modpack and with all modpacks in version 1.14.4, those in version 1.12.2 open normally. and native version have equals problem

**Comment by crunchynut609** [comment]
> go to settings -> minecraft -> Launcher -> Launcher Method and set it to Native, that fixed it for me

whenever I switch to the native launcher it automatically just switches back to the java launcher

**Comment by crunchynut609** [comment]
I am having the same problem with all of my modpacks, even 1.12 ones like project ozone 3

**Comment by Alucabr** [comment]
ok ftb, curse and twitch 
They don't care about the problems, what's happening?

**Comment by crunchynut609** [comment]
> ok ftb, curse and twitch
> They don't care about the problems, what's happening?

okay so, I press play on the modpack on twitch, and like normal it opens the jar launcher.

BUT the when you would normally press play on the launcher, it constantly says "loading" and under my username to the bottom right it says "loading versions"

I have tried many different things to fix the problem but nothing has worked. it seems to be a problem that started occurring after the last update for twitch, because now I cannot play any of my modpacks.

**Comment by crunchynut609** [comment]
> ok ftb, curse and twitch
> They don't care about the problems, what's happening?

and about the native launcher.

whenever I select it in settings > minecraft on twitch, it just automatically switches back to the jar launcher after I close the setting tab.

**Comment by Sunekaer** [comment]
Im sorry theres nothing i can do about launcher issues, youll need to contact twitch, as this is a launcher crash.
