### ISSUE TITLE
Launcher stuck on loading

### ISSUE THREAD

**Issue by WaffleSaleks** [FTBTeam/FTB-Unstable-1.14#36]
The lancher remains stuck with the loading button , here's the Launcher Log
https://paste.feed-the-beast.com/view/c8c287fb

**Comment by Beatzoid** [comment]
Same. Thought it was just my internet lol.

**Comment by WaffleSaleks** [comment]
I solved it somehow
First i found out which forge version i needed,installed that onto my normal minecraft 
After that i just chosen the forge version in the native launcher and put in the game directory where twitch/FTB stores the modpack files.
Its convenient in a way and also theres no need to use the twitch launcer
