### ISSUE TITLE
Twitch launcher doesn't even try to install

### ISSUE THREAD

**Issue by Dosmish** [FTBTeam/FTB-Unstable-1.14#39]
After I click install it says that it can't find a specific folder. Idk, other modpacks work but Unstable 1.14.x just doesn't work if more info is needed i'll send. Thx

**Comment by Tkdriverx** [comment]
I am having this issue as well.
![image](https://user-images.githubusercontent.com/9004164/67642038-234a2280-f8de-11e9-9ec4-9fe393274580.png)

**Comment by Sunekaer** [comment]
Please report to twitch, nothing we can do about this.
