### ISSUE TITLE
[Request] Add Apotheosis

### ISSUE THREAD

**Issue by Shadows-of-Fire** [FTBTeam/FTB-Unstable-1.14#4]
https://www.curseforge.com/minecraft/mc-mods/apotheosis

Apotheosis provides a lot of expansion to enchanting and spawners, and I think it would be helpful to have it in unstable not only for the content it provides to players, but for testing it to see how well it does alongside the other mods in the 1.14 ecosystem.

Additionally, it provides a reason to use vanilla tools over silent's tools, allows for mob farms (which no other mod appears to provide yet), and adds some more exploration value in the form of randomly generated spawners, bosses, and wandering merchant upgrades.

**Comment by Sunekaer** [comment]
[1.4.0](https://www.feed-the-beast.com/projects/ftb-unstable-1-14/files/2763443)

**Comment by keremlov** [comment]
they actually added wow , love ftb :)
