### ISSUE TITLE
Modpack crashes on startup

### ISSUE THREAD

**Issue by MelanX** [FTBTeam/FTB-Unstable-1.14#40]
I just downloaded 1.10.0 and it crashes everytime cause of Forbidden and Arcanus. Reported the bug here: https://github.com/stal111/Forbidden-Arcanus/issues/17

But removing this mod still doesn't help. Another crash log is shown:
https://pastebin.com/7hU4QytP

Change forge version back to 28.1.39 let the pack start.

**Comment by MelanX** [comment]
Oops it still crashes with Forbidden and Arcanus. Forgot to re-add it when testing with Forge 28.1.39.
Downgrade Forbidden and Arcanus to 1.3 (like in Unstable 1.14-1.9.0) helps to launch the pack.

**Comment by jikuja** [comment]
Please, close. Caused by optifine but OP did not update ticket.
