### ISSUE TITLE
Where are the Server Files

### ISSUE THREAD

**Issue by Thebettermaker** [FTBTeam/FTB-Unstable-1.14#49]
Hey the Problem I have witch FTB Unstable 1.14 that there are no Server Files and me and my friends like this pack and want to play it together but we can't because we have no Serverfiles. But first we don't know that so we bought a server but we can't play the modpack that we want please give us the MODPACK!!

**Comment by Sunekaer** [comment]
Hi,
We dont do server files for our unstable packs.
Even if i wanted to i cant, as all the mods in the packs doesnt work on server atm.
