### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by mortghenn** [FTBTeam/FTB-Unstable-1.14#8]
I have two mod suggestions for the pack. Both of these mods are exclusively for 1.14 and are being constantly updated. I wholeheartedly believe FTB can give them the spotlight they deserve.
1. [Simple Farming](https://www.curseforge.com/minecraft/mc-mods/simple-farming). Extends Minecraft's agricultural field with more crops and food.
2. [Upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic). Improves all things ocean related through a myriad of new mobs and miscellaneous features.

**Comment by Sunekaer** [comment]
Upgrade Aquatic added.
Simple Farming wont be added as there is many other mods in adding foods

**Comment by mortghenn** [comment]
Awesome! Would still love for simple farming to be in the pack as there is a pretty big lack of good meals/food and replenish a lot of hunger
